// Generated by Garatch Designer
// Project: basic

using Toybox.Graphics;
using Toybox.WatchUi;
using Toybox.System;
using Toybox.Time;
using Toybox.Time.Gregorian;

class BasicView extends WatchUi.WatchFace {
    private var _w;
    private var _h;
    private var _cx;
    private var _cy;

    function initialize() {
        WatchFace.initialize();
    }

    function onLayout(dc) as Void {
        _w = dc.getWidth();
        _h = dc.getHeight();
        _cx = _w / 2;
        _cy = _h / 2;
    }

    function onUpdate(dc) as Void {
        // Background
        dc.setColor(Graphics.COLOR_BLACK, Graphics.COLOR_BLACK);
        dc.clear();

        // Draw elements
        drawElement0(dc);
        drawElement1(dc);
    }

    function onHide() as Void {
    }

    function onExitSleep() as Void {
    }

    function onEnterSleep() as Void {
    }

    // ========== Element Drawing Functions ==========

    function drawElement0(dc) {
        var clockTime = System.getClockTime();
        var hour = clockTime.hour;

        var timeStr = hour.format("%02d") + ":" + clockTime.min.format("%02d");

        dc.setColor(Graphics.COLOR_WHITE, Graphics.COLOR_TRANSPARENT);
        dc.drawText(160, 180, Graphics.FONT_SYSTEM_NUMBER_HOT, timeStr, Graphics.TEXT_JUSTIFY_CENTER | Graphics.TEXT_JUSTIFY_VCENTER);
    }

    function drawElement1(dc) {
        var stats = System.getSystemStats();
        var battery = stats.battery.toNumber();

        // Battery outline
        dc.setColor(Graphics.COLOR_WHITE, Graphics.COLOR_TRANSPARENT);
        dc.setPenWidth(2);
        dc.drawRectangle(20, 20, 46, 24);

        // Battery cap
        dc.fillRectangle(66, 26, 4, 12);

        // Battery fill with color based on level

    var batColor = Graphics.COLOR_GREEN;
    if (battery <= 20) {
        batColor = Graphics.COLOR_RED;
    } else if (battery <= 50) {
        batColor = Graphics.COLOR_YELLOW;
    }
        dc.setColor(batColor, Graphics.COLOR_TRANSPARENT);
        var fillWidth = ((42) * battery) / 100;
        dc.fillRectangle(22, 22, fillWidth, 20);
    }
}
