// Generated by Garatch Designer
// Project: basic

using Toybox.Application;
using Toybox.WatchUi;

class BasicApp extends Application.AppBase {
    function initialize() {
        AppBase.initialize();
    }

    function onStart(state) as Void {
    }

    function onStop(state) as Void {
    }

    function getInitialView() {
        return [ new BasicView() ];
    }
}
