import { DEFAULT_FONT_HEIGHTS, DEFAULT_LETTER_SPACING } from "./bmfont.js";

const face = (id, name, description, category, accent, fontFamily, elements, overrides = {}) => ({
  id, name, description, category, accent, fontFamily, elements, ...overrides,
});

export const WATCH_TEMPLATES = [
  face("night-signal", "Night Circuit", "An asymmetric command deck with live motion and charge rings.", "Data", "#72D6B2", "barlow-condensed", [
    { type: "rectangle", x: 0, y: 0, width: 320, height: 78, fillColor: "#10231D", cornerRadius: 0 },
    { type: "rectangle", x: 214, y: 78, width: 106, height: 282, fillColor: "#09110F", cornerRadius: 0 },
    { type: "rectangle", x: 20, y: 96, width: 4, height: 225, fillColor: "#72D6B2", cornerRadius: 2 },
    { type: "label", x: 20, y: 38, text: "NIGHT / CIRCUIT", color: "#72D6B2", align: "left", maxWidth: 184, lineHeight: 18 },
    { type: "date", x: 294, y: 39, color: "#FFFFFF", align: "right", representation: "full-date" },
    { type: "time", x: 112, y: 168, color: "#72D6B2", align: "center", format: "hour24", showSeconds: false, representation: "seconds-ring" },
    { type: "steps", x: 230, y: 138, color: "#BFF4E1", align: "left", representation: "goal-ring", progressMax: 10000 },
    { type: "battery", x: 230, y: 216, color: "#72D6B2", align: "left", representation: "goal-ring" },
    { type: "label", x: 40, y: 268, text: "PULSE TRACE", color: "#4E7467", align: "left", maxWidth: 120, lineHeight: 16 },
    { type: "heart-rate", x: 40, y: 300, color: "#FF7A70", align: "left", representation: "history-graph" },
    { type: "stress", x: 258, y: 310, color: "#B794F6", align: "center", representation: "icon" },
    { type: "stress", x: 294, y: 310, color: "#B794F6", align: "right", representation: "value" },
  ], { backgroundColor: "#030706", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("orbit-analog", "Orbit", "A celestial instrument dial with health zones and twin goals.", "Analog", "#F4D06F", "space-grotesk", [
    { type: "ellipse", x: 135, y: 144, radiusX: 105, radiusY: 105, fillColor: "#15140F" },
    { type: "rectangle", x: 250, y: 0, width: 70, height: 360, fillColor: "#100F0A", cornerRadius: 0 },
    { type: "label", x: 24, y: 33, text: "ORBIT / 24", color: "#6F6746", align: "left", maxWidth: 120, lineHeight: 16 },
    { type: "date", x: 286, y: 58, color: "#F4D06F", align: "center", representation: "calendar" },
    { type: "time", x: 135, y: 144, color: "#F4D06F", align: "center", format: "device", showSeconds: true, representation: "analog" },
    { type: "heart-rate", x: 24, y: 244, color: "#FF7A70", align: "left", representation: "value", progressMax: 200 },
    { type: "heart-rate", x: 24, y: 276, color: "#FF7A70", align: "left", representation: "zone-gauge", progressMax: 200 },
    { type: "steps", x: 40, y: 318, color: "#FFFFFF", align: "left", representation: "goal-ring", progressMax: 10000 },
    { type: "battery", x: 198, y: 318, color: "#F4D06F", align: "left", representation: "goal-ring" },
  ], { backgroundColor: "#050504", fontHeights: { time: 72, value: 24, label: 18 } }),
  face("instrument-hybrid", "Instrument", "Analog motion paired with a crisp digital readout.", "Analog", "#82C8FF", "oxanium", [
    { type: "rectangle", x: 18, y: 18, width: 284, height: 324, fillColor: "#09131B", cornerRadius: 28 },
    { type: "label", x: 160, y: 45, text: "FIELD / 07", color: "#82C8FF", align: "center", maxWidth: 220, lineHeight: 18 },
    { type: "time", x: 160, y: 142, color: "#FFFFFF", align: "center", format: "hour24", showSeconds: false, representation: "analog-digital" },
    { type: "date", x: 160, y: 240, color: "#82C8FF", align: "center", representation: "month-day" },
    { type: "steps", x: 82, y: 300, color: "#C6E7FF", align: "center", representation: "goal-ring", progressMax: 10000 },
    { type: "battery", x: 238, y: 300, color: "#82C8FF", align: "center", representation: "goal-ring" },
  ], { backgroundColor: "#03080C", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("seconds-halo", "Seconds Reactor", "A live seconds core surrounded by pulse and stress telemetry.", "Digital", "#FF715B", "rajdhani", [
    { type: "rectangle", x: 0, y: 0, width: 92, height: 360, fillColor: "#27110E", cornerRadius: 0 },
    { type: "rectangle", x: 92, y: 0, width: 228, height: 72, fillColor: "#160C0A", cornerRadius: 0 },
    { type: "ellipse", x: 202, y: 148, radiusX: 86, radiusY: 86, fillColor: "#130B09" },
    { type: "label", x: 112, y: 37, text: "SECONDS / REACTOR", color: "#FF715B", align: "left", maxWidth: 180, lineHeight: 16 },
    { type: "date", x: 46, y: 92, color: "#FF9B8D", align: "center", representation: "calendar" },
    { type: "time", x: 202, y: 148, color: "#FF715B", align: "center", format: "hour24", showSeconds: false, representation: "seconds-ring" },
    { type: "label", x: 24, y: 247, text: "PULSE", color: "#7B4B45", align: "left", maxWidth: 70, lineHeight: 14 },
    { type: "heart-rate", x: 24, y: 278, color: "#FF715B", align: "left", representation: "history-graph" },
    { type: "stress", x: 176, y: 256, color: "#B794F6", align: "left", representation: "value" },
    { type: "stress", x: 176, y: 288, color: "#B794F6", align: "left", representation: "zone-gauge" },
    { type: "battery", x: 262, y: 330, color: "#FFFFFF", align: "center", representation: "icon" },
    { type: "battery", x: 296, y: 330, color: "#FFFFFF", align: "right", representation: "value" },
  ], { backgroundColor: "#080403", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("metric-grid", "Metric Mosaic", "Interlocking data tiles with goals, calendar, and pulse history.", "Data", "#8CC8FF", "rajdhani", [
    { type: "rectangle", x: 16, y: 16, width: 136, height: 136, fillColor: "#0B1B29", cornerRadius: 24 },
    { type: "rectangle", x: 168, y: 16, width: 136, height: 136, fillColor: "#15131F", cornerRadius: 24 },
    { type: "rectangle", x: 16, y: 168, width: 288, height: 176, fillColor: "#080D12", cornerRadius: 24 },
    { type: "label", x: 34, y: 42, text: "METRIC", color: "#587D9D", align: "left", maxWidth: 90, lineHeight: 14 },
    { type: "time", x: 160, y: 98, color: "#FFFFFF", align: "center", format: "hour24", showSeconds: false, representation: "split" },
    { type: "date", x: 62, y: 218, color: "#8CC8FF", align: "center", representation: "calendar" },
    { type: "steps", x: 132, y: 218, color: "#72D6B2", align: "left", representation: "goal-ring", progressMax: 10000 },
    { type: "calories", x: 226, y: 218, color: "#F5B45E", align: "left", representation: "goal-ring", progressMax: 500 },
    { type: "heart-rate", x: 34, y: 300, color: "#F1847C", align: "left", representation: "history-graph" },
    { type: "battery", x: 252, y: 320, color: "#91D6B8", align: "center", representation: "icon" },
    { type: "battery", x: 286, y: 320, color: "#91D6B8", align: "right", representation: "value" },
  ], { backgroundColor: "#020507", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("pulse-trace", "Pulse Trace", "Live heart and stress history in a training layout.", "Wellness", "#FF7A70", "archivo-narrow", [
    { type: "rectangle", x: 0, y: 0, width: 320, height: 72, fillColor: "#1B0C0D", cornerRadius: 0 },
    { type: "time", x: 22, y: 38, color: "#FFFFFF", align: "left", format: "hour24", showSeconds: false, representation: "value" },
    { type: "date", x: 295, y: 38, color: "#FF7A70", align: "right", representation: "weekday" },
    { type: "label", x: 24, y: 112, text: "HEART RATE", color: "#7F696A", align: "left", maxWidth: 150, lineHeight: 18 },
    { type: "heart-rate", x: 24, y: 150, color: "#FF7A70", align: "left", representation: "history-graph" },
    { type: "label", x: 24, y: 230, text: "STRESS", color: "#71677D", align: "left", maxWidth: 150, lineHeight: 18 },
    { type: "stress", x: 24, y: 266, color: "#B794F6", align: "left", representation: "history-graph" },
    { type: "battery", x: 262, y: 326, color: "#8A9299", align: "center", representation: "icon" },
    { type: "battery", x: 296, y: 326, color: "#8A9299", align: "right", representation: "value" },
  ], { backgroundColor: "#080506", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("goal-orbits", "Goal Orbits", "Color-coded rings for movement, energy, and range.", "Data", "#72D6B2", "space-grotesk", [
    { type: "date", x: 160, y: 40, color: "#78807C", align: "center", representation: "full-date" },
    { type: "time", x: 160, y: 104, color: "#FFFFFF", align: "center", format: "device", showSeconds: false, representation: "value" },
    { type: "steps", x: 64, y: 210, color: "#72D6B2", align: "center", representation: "goal-ring", progressMax: 10000 },
    { type: "calories", x: 160, y: 210, color: "#F5B45E", align: "center", representation: "goal-ring", progressMax: 500 },
    { type: "distance", x: 256, y: 210, color: "#8CC8FF", align: "center", representation: "goal-ring", progressMax: 5, unit: "kilometers" },
    { type: "label", x: 64, y: 268, text: "STEPS", color: "#58605C", align: "center", maxWidth: 72, lineHeight: 16 },
    { type: "label", x: 160, y: 268, text: "CAL", color: "#665D4E", align: "center", maxWidth: 72, lineHeight: 16 },
    { type: "label", x: 256, y: 268, text: "KM", color: "#536373", align: "center", maxWidth: 72, lineHeight: 16 },
    { type: "battery", x: 160, y: 326, color: "#FFFFFF", align: "center", representation: "progress-bar" },
  ], { fontHeights: { time: 72, value: 24, label: 14 } }),
  face("minimal-halo", "Minimal Halo", "A soft geometric frame with only essentials.", "Minimal", "#D9B7FF", "space-grotesk", [
    { type: "ellipse", x: 160, y: 176, radiusX: 118, radiusY: 118, fillColor: "#17131E" },
    { type: "icon", x: 160, y: 76, icon: "sun", style: "outline", size: 24, color: "#D9B7FF" },
    { type: "time", x: 160, y: 158, color: "#FFFFFF", align: "center", format: "device", showSeconds: false, representation: "value" },
    { type: "date", x: 160, y: 216, color: "#B9ACCA", align: "center", representation: "month-day" },
    { type: "battery", x: 142, y: 322, color: "#D9B7FF", align: "center", representation: "icon" },
    { type: "battery", x: 158, y: 322, color: "#D9B7FF", align: "left", representation: "value" },
  ], { fontHeights: { time: 88, value: 30, label: 18 } }),
  face("sport-split", "Sport Split", "Bold split time paired with training metrics.", "Digital", "#F5B45E", "oxanium", [
    { type: "rectangle", x: 0, y: 0, width: 12, height: 360, fillColor: "#F5B45E", cornerRadius: 0 },
    { type: "label", x: 34, y: 42, text: "MOVE / RECOVER", color: "#F5B45E", align: "left", maxWidth: 250, lineHeight: 20 },
    { type: "time", x: 160, y: 116, color: "#FFFFFF", align: "center", format: "hour24", showSeconds: false, representation: "split" },
    { type: "steps", x: 34, y: 224, color: "#FFFFFF", align: "left", representation: "progress-bar", progressMax: 10000 },
    { type: "heart-rate", x: 202, y: 206, color: "#F1847C", align: "left", representation: "value", progressMax: 200 },
    { type: "heart-rate", x: 202, y: 238, color: "#F1847C", align: "left", representation: "zone-gauge", progressMax: 200 },
    { type: "distance", x: 34, y: 310, color: "#8CC8FF", align: "left", unit: "kilometers", representation: "icon" },
    { type: "distance", x: 58, y: 310, color: "#8CC8FF", align: "left", unit: "kilometers", representation: "value" },
  ], { fontHeights: { time: 72, value: 30, label: 14 } }),
  face("linear", "Solar Transit", "A split-time solar composition with calendar and stress telemetry.", "Digital", "#FFB14E", "archivo-narrow", [
    { type: "ellipse", x: 246, y: 82, radiusX: 72, radiusY: 72, fillColor: "#2A1608" },
    { type: "rectangle", x: 0, y: 0, width: 18, height: 360, fillColor: "#FFB14E", cornerRadius: 0 },
    { type: "rectangle", x: 18, y: 190, width: 302, height: 2, fillColor: "#50331A", cornerRadius: 0 },
    { type: "label", x: 42, y: 38, text: "SOLAR TRANSIT", color: "#FFB14E", align: "left", maxWidth: 170, lineHeight: 16 },
    { type: "time", x: 160, y: 126, color: "#FFFFFF", align: "center", format: "hour24", showSeconds: false, representation: "split" },
    { type: "date", x: 62, y: 246, color: "#FFB14E", align: "center", representation: "calendar" },
    { type: "label", x: 132, y: 220, text: "STRESS FLUX", color: "#82654D", align: "left", maxWidth: 110, lineHeight: 16 },
    { type: "stress", x: 132, y: 254, color: "#B794F6", align: "left", representation: "history-graph" },
    { type: "steps", x: 42, y: 326, color: "#FFB14E", align: "left", representation: "progress-bar", progressMax: 10000 },
    { type: "battery", x: 262, y: 326, color: "#FFFFFF", align: "center", representation: "icon" },
    { type: "battery", x: 296, y: 326, color: "#FFFFFF", align: "right", representation: "value" },
  ], { backgroundColor: "#090603", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("recovery", "Recovery", "Wellness zones with space to breathe.", "Wellness", "#B794F6", "barlow-condensed", [
    { type: "label", x: 24, y: 38, text: "RECOVERY", color: "#B794F6", align: "left", maxWidth: 180, lineHeight: 18 },
    { type: "date", x: 296, y: 38, color: "#81788C", align: "right", representation: "weekday" },
    { type: "time", x: 24, y: 104, color: "#FFFFFF", align: "left", format: "device", showSeconds: false, representation: "value" },
    { type: "line", x: 24, y: 154, endX: 296, endY: 154, color: "#2A2430", thickness: 1 },
    { type: "label", x: 24, y: 190, text: "HEART", color: "#756D79", align: "left", maxWidth: 72, lineHeight: 16 },
    { type: "heart-rate", x: 24, y: 204, color: "#FF7A70", align: "left", representation: "value", progressMax: 200 },
    { type: "heart-rate", x: 24, y: 236, color: "#FF7A70", align: "left", representation: "zone-gauge", progressMax: 200 },
    { type: "label", x: 184, y: 190, text: "STRESS", color: "#756D79", align: "left", maxWidth: 72, lineHeight: 16 },
    { type: "stress", x: 184, y: 204, color: "#B794F6", align: "left", representation: "value" },
    { type: "stress", x: 184, y: 236, color: "#B794F6", align: "left", representation: "zone-gauge" },
    { type: "steps", x: 24, y: 310, color: "#72D6B2", align: "left", representation: "icon" },
    { type: "steps", x: 48, y: 310, color: "#72D6B2", align: "left", representation: "value" },
    { type: "battery", x: 262, y: 310, color: "#FFFFFF", align: "center", representation: "icon" },
    { type: "battery", x: 296, y: 310, color: "#FFFFFF", align: "right", representation: "value" },
  ], { backgroundColor: "#09070B", fontHeights: { time: 72, value: 24, label: 14 } }),
  face("big-time", "Chromatic Stack", "Architectural time blocks with a live performance rail.", "Digital", "#FF6B5E", "oswald", [
    { type: "rectangle", x: 0, y: 0, width: 126, height: 360, fillColor: "#36131C", cornerRadius: 0 },
    { type: "rectangle", x: 126, y: 0, width: 12, height: 360, fillColor: "#FF6B5E", cornerRadius: 0 },
    { type: "rectangle", x: 150, y: 28, width: 146, height: 116, fillColor: "#171218", cornerRadius: 20 },
    { type: "label", x: 26, y: 35, text: "CHROMA / 08", color: "#FF998F", align: "left", maxWidth: 90, lineHeight: 16 },
    { type: "time", x: 66, y: 165, color: "#FFFFFF", align: "center", format: "device", showSeconds: false, representation: "stacked" },
    { type: "date", x: 223, y: 84, color: "#FF6B5E", align: "center", representation: "calendar" },
    { type: "label", x: 164, y: 181, text: "MOVE INDEX", color: "#75636C", align: "left", maxWidth: 110, lineHeight: 16 },
    { type: "steps", x: 164, y: 216, color: "#72D6B2", align: "left", representation: "progress-bar", progressMax: 10000 },
    { type: "heart-rate", x: 164, y: 258, color: "#FF6B5E", align: "left", representation: "value", progressMax: 200 },
    { type: "heart-rate", x: 164, y: 290, color: "#FF6B5E", align: "left", representation: "zone-gauge", progressMax: 200 },
    { type: "battery", x: 262, y: 330, color: "#FFFFFF", align: "center", representation: "icon" },
    { type: "battery", x: 296, y: 330, color: "#FFFFFF", align: "right", representation: "value" },
  ], { backgroundColor: "#080609", fontHeights: { time: 72, value: 24, label: 14 } }),
];

export function createProjectFromTemplate(templateId = "night-signal") {
  const template = WATCH_TEMPLATES.find((item) => item.id === templateId) ?? WATCH_TEMPLATES[0];
  return {
    name: template.name,
    appId: crypto.randomUUID().replaceAll("-", ""),
    backgroundColor: template.backgroundColor ?? "#000000",
    fontFamily: template.fontFamily,
    fontFamilySecondary: template.fontFamilySecondary ?? template.fontFamily,
    fontHeights: { ...DEFAULT_FONT_HEIGHTS, ...template.fontHeights },
    letterSpacing: { ...DEFAULT_LETTER_SPACING, ...template.letterSpacing },
    elements: template.elements.map((element) => ({
      ...structuredClone(element),
      ...(element.type === "icon" ? { style: element.style ?? "filled" } : {}),
      id: `${element.type}-${crypto.randomUUID().replaceAll("-", "").slice(0, 8)}`,
    })),
  };
}
