/**
 * Generate App.mc file content
 */

import type { WatchFaceProject } from '@/store/types'
import { toClassName } from '../utils/naming'

export function generateAppMc(project: WatchFaceProject): string {
  const className = toClassName(project.name) + 'App'
  const viewClassName = toClassName(project.name) + 'View'

  return `// Generated by Garatch Designer
// Project: ${project.name}

using Toybox.Application;
using Toybox.WatchUi;

class ${className} extends Application.AppBase {
    function initialize() {
        AppBase.initialize();
    }

    function onStart(state) as Void {
    }

    function onStop(state) as Void {
    }

    function getInitialView() {
        return [ new ${viewClassName}() ];
    }
}
`
}
