/**
 * Generate monkey.jungle file content
 */

import type { WatchFaceProject } from '@/store/types'
import { requiresPixelFontModule } from '../renderers'

export function generateMonkeyJungle(project: WatchFaceProject): string {
  const needsPixelFont = requiresPixelFontModule(project.elements)

  // Base source paths
  let sourcePaths = 'source'

  // Add shared modules if needed
  if (needsPixelFont) {
    sourcePaths = 'source;../../shared/source'
  }

  return `# Generated by Garatch Designer
# Project: ${project.name}

project.manifest = manifest.xml
project.sourcePath = ${sourcePaths}
project.resourcePath = resources
project.optimization = 2
`
}
