/**
 * Generate manifest.xml file content
 */

import type { WatchFaceProject } from '@/store/types'
import { toClassName, generateAppId } from '../utils/naming'

export function generateManifestXml(project: WatchFaceProject): string {
  const className = toClassName(project.name) + 'App'
  const appId = generateAppId()
  const device = project.settings.targetDevice || 'venusq2'

  // Determine required permissions based on elements
  const hasSteps = project.elements.some((el) => el.type === 'steps')
  const hasHeartRate = project.elements.some((el) => el.type === 'heart-rate')

  const permissions: string[] = []
  if (hasSteps || hasHeartRate) {
    permissions.push('UserProfile')
    permissions.push('SensorHistory')
  }

  const permissionsXml = permissions.length > 0
    ? `
    <iq:permissions>
${permissions.map((p) => `        <iq:uses-permission id="${p}"/>`).join('\n')}
    </iq:permissions>`
    : ''

  return `<?xml version="1.0"?>
<!-- Generated by Garatch Designer -->
<iq:manifest xmlns:iq="http://www.garmin.com/xml/connectiq" version="3">
    <iq:application entry="${className}" id="${appId}"
                    launcherIcon="@Drawables.LauncherIcon"
                    minSdkVersion="3.2.0"
                    name="@Strings.AppName"
                    type="watchface"
                    version="1.0.0">
        <iq:products>
            <iq:product id="${device}"/>
            ${device === 'venusq2' ? '<iq:product id="venusq2m"/>' : ''}
        </iq:products>${permissionsXml}
        <iq:languages>
            <iq:language>eng</iq:language>
        </iq:languages>
        <iq:barrels/>
    </iq:application>
</iq:manifest>
`
}
