/**
 * Generate resource files content
 */

import type { WatchFaceProject } from '@/store/types'

export function generateDrawablesXml(): string {
  return `<?xml version="1.0"?>
<!-- Generated by Garatch Designer -->
<drawables>
    <bitmap id="LauncherIcon" filename="launcher_icon.png" />
</drawables>
`
}

export function generateStringsXml(project: WatchFaceProject): string {
  return `<?xml version="1.0"?>
<!-- Generated by Garatch Designer -->
<strings>
    <string id="AppName">${project.name}</string>
</strings>
`
}

export function generateLayoutXml(): string {
  return `<?xml version="1.0"?>
<!-- Generated by Garatch Designer -->
<layout id="WatchFace">
</layout>
`
}
