/**
 * Generate View.mc file content
 */

import type { WatchFaceProject } from '@/store/types'
import { toClassName } from '../utils/naming'
import { renderElement, renderElementCall } from '../renderers'

export function generateViewMc(project: WatchFaceProject): string {
  const className = toClassName(project.name) + 'View'
  const elements = project.elements

  // Sort elements by zIndex for proper drawing order
  const sortedElements = [...elements].sort(
    (a, b) => a.properties.zIndex - b.properties.zIndex
  )

  // Find background element (if any)
  const bgElement = sortedElements.find((el) => el.type === 'background')
  const otherElements = sortedElements.filter((el) => el.type !== 'background')

  // Generate imports
  const imports = [
    'using Toybox.Graphics;',
    'using Toybox.WatchUi;',
    'using Toybox.System;',
    'using Toybox.Time;',
    'using Toybox.Time.Gregorian;',
  ]

  // Add conditional imports based on elements used
  const hasSteps = elements.some((el) => el.type === 'steps')
  const hasHeartRate = elements.some((el) => el.type === 'heart-rate')
  const hasAnalog = elements.some((el) => el.type === 'time-analog')

  if (hasSteps) {
    imports.push('using Toybox.ActivityMonitor;')
  }
  if (hasHeartRate) {
    imports.push('using Toybox.Activity;')
  }
  if (hasAnalog) {
    imports.push('using Toybox.Math;')
  }

  // Generate background code
  let backgroundCode = `        // Background
        dc.setColor(Graphics.COLOR_BLACK, Graphics.COLOR_BLACK);
        dc.clear();`

  if (bgElement) {
    backgroundCode = renderElement(bgElement, -1)
  }

  // Generate element drawing functions
  const elementFunctions = otherElements
    .map((el, idx) => renderElement(el, idx))
    .filter((code) => code.trim().length > 0)
    .join('\n')

  // Generate element calls in onUpdate
  const elementCalls = otherElements
    .map((el, idx) => renderElementCall(el, idx))
    .filter((call) => call.trim().length > 0)
    .join('\n')

  return `// Generated by Garatch Designer
// Project: ${project.name}

${imports.join('\n')}

class ${className} extends WatchUi.WatchFace {
    private var _w;
    private var _h;
    private var _cx;
    private var _cy;

    function initialize() {
        WatchFace.initialize();
    }

    function onLayout(dc) as Void {
        _w = dc.getWidth();
        _h = dc.getHeight();
        _cx = _w / 2;
        _cy = _h / 2;
    }

    function onUpdate(dc) as Void {
${backgroundCode}

        // Draw elements
${elementCalls}
    }

    function onHide() as Void {
    }

    function onExitSleep() as Void {
    }

    function onEnterSleep() as Void {
    }

    // ========== Element Drawing Functions ==========
${elementFunctions}
}
`
}
