import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { Resvg } from "@resvg/resvg-js";

const root = resolve(import.meta.dirname, "..");
const sourceRoot = resolve(root, "node_modules/phosphor-svelte/lib");
const outputRoot = resolve(root, "assets/icons");
const generatedModule = resolve(root, "ui/lib/phosphorIconPaths.generated.js");
const licenseOutput = resolve(outputRoot, "Phosphor-MIT.txt");
const icons = {
  heart: "HeartIcon",
  steps: "FootprintsIcon",
  battery: "BatteryHighIcon",
  flame: "FireIcon",
  pin: "MapPinIcon",
  sun: "SunIcon",
  bolt: "LightningIcon",
};
const weights = { filled: "fill", outline: "regular" };

function pathForWeight(source, weight) {
  const marker = new RegExp(`\\{(?::else if|#if) weight === "${weight}"\\}([\\s\\S]*?)(?=\\{:else|\\{/if\\})`);
  const block = source.match(marker)?.[1];
  const path = block?.match(/<path d="([^"]+)"/)?.[1];
  if (!path) throw new Error(`Could not extract ${weight} path`);
  return path;
}

await mkdir(outputRoot, { recursive: true });
await writeFile(
  licenseOutput,
  await readFile(resolve(root, "node_modules/phosphor-svelte/LICENSE")),
);
const paths = {};
for (const [name, component] of Object.entries(icons)) {
  const source = await readFile(resolve(sourceRoot, `${component}.svelte`), "utf8");
  paths[name] = {};
  for (const [style, weight] of Object.entries(weights)) {
    const path = pathForWeight(source, weight);
    paths[name][style] = path;
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 256 256"><path fill="#ffffff" d="${path}"/></svg>`;
    const png = new Resvg(svg, { fitTo: { mode: "width", value: 96 } }).render().asPng();
    await writeFile(resolve(outputRoot, `${name}_${style}.png`), png);
  }
}

await writeFile(
  generatedModule,
  `// Generated by scripts/build_icon_assets.mjs from phosphor-svelte.\nexport const PHOSPHOR_ICON_PATHS = ${JSON.stringify(paths, null, 2)};\n`,
);
